import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { 
  LifeBuoy, 
  Search, 
  ChevronDown, 
  MessageCircleQuestion, 
  FileText, 
  ShieldCheck, 
  CreditCard, 
  Briefcase,
  ExternalLink,
  Mail
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAuth } from '../../context/AuthContext';

const FAQ_DATA = [
  {
    category: "Getting Started & Vetting",
    icon: ShieldCheck,
    questions: [
      {
        q: "Why do I need to complete the vetting process?",
        a: "To maintain a high standard of quality and trust on the OpsBridge platform, all service providers must be verified. Vetting ensures that our clients are matched with legitimate, qualified businesses for their operational expansion needs."
      },
      {
        q: "How long does the vetting process take?",
        a: "The initial vetting process typically takes 1-3 business days. You will be notified via email and in-app notifications once your profile has been approved by an administrator."
      },
      {
        q: "What happens if my vetting application is rejected?",
        a: "If your application requires more information or is rejected, you will receive a notification outlining the specific reasons. You can update your profile and resubmit your application at any time."
      }
    ]
  },
  {
    category: "Documents & Security",
    icon: FileText,
    questions: [
      {
        q: "What documents are required to activate my provider account?",
        a: "You must upload a valid Government-issued Identification Document (e.g., Passport, Driver's License) and your Company's Certificate of Incorporation. These must be uploaded in the 'Documents' tab."
      },
      {
        q: "Is my sensitive documentation secure?",
        a: "Yes. All files uploaded to OpsBridge, including your identification, incorporation certificates, and voided checks, are protected with military-grade AES-256 encryption. Only authorized personnel and your assigned clients have access."
      },
      {
        q: "Can I upload general files to my repository?",
        a: "Absolutely. You can use the 'Upload General File' button in the Documents tab to securely store any business-related files up to 10MB in size."
      }
    ]
  },
  {
    category: "Projects & Agreements",
    icon: Briefcase,
    questions: [
      {
        q: "How do I apply for a project?",
        a: "Navigate to the 'Projects' tab to browse open opportunities. Click on a project to view its Scope of Work. If you are a verified provider, you can use the rich-text editor to submit a detailed proposal directly to the client."
      },
      {
        q: "What happens after a client accepts my proposal?",
        a: "When a client accepts your proposal, you are officially assigned to the project. However, before you can view or accept tasks, you must electronically sign a Mutual Non-Disclosure Agreement (NDA) and a Memorandum of Understanding (MOU) generated by the platform."
      },
      {
        q: "How do I sign the NDA and MOU?",
        a: "Go to your 'Tasks' tab. If you have pending agreements, the task board will be locked, and you will see an 'Agreements Pending' prompt. Click 'Sign', read the document, and type your full legal name to electronically accept the terms."
      }
    ]
  },
  {
    category: "Task Management",
    icon: MessageCircleQuestion,
    questions: [
      {
        q: "How do I communicate with a client about a specific task?",
        a: "Each task has its own dedicated details modal. Click on any task to open it. Inside, you will find a real-time comment thread where you can send messages and discuss deliverables directly with the client."
      },
      {
        q: "How do I submit deliverables or files for a task?",
        a: "Inside the task details modal, use the paperclip icon (📎) next to the comment input box to upload and attach files (up to 15MB) directly to the conversation."
      },
      {
        q: "How do I update the status of a task?",
        a: "You can update a task's status (Pending, In Progress, or Completed) using the dropdown menu located on the task card in the list view, or from within the task details modal. Changing a status automatically notifies the client."
      }
    ]
  },
  {
    category: "Payments & Billing",
    icon: CreditCard,
    questions: [
      {
        q: "How do I set up my payment information?",
        a: "Navigate to the 'Payments' tab. You will be prompted to enter your bank name, account holder name, account number, and routing number. You must also upload a clear copy of a voided check or bank letter for verification."
      },
      {
        q: "Who processes the payments on OpsBridge?",
        a: "All platform payments are securely processed by American Express. We do not store your raw banking credentials directly on our servers without encryption."
      },
      {
        q: "When will I receive my funds?",
        a: "Once a client schedules a payment, the funds are immediately debited from their account and the payment cannot be cancelled. When the status changes to 'Paid Out' in your dashboard, please allow 1-5 business days for the funds to clear into your designated bank account."
      },
      {
        q: "Why is my payment profile marked as 'Verification Pending'?",
        a: "For security and compliance, an OpsBridge administrator must manually review and approve your banking details and voided check before you can receive payouts. This process typically takes 1-2 business days."
      },
      {
        q: "Can a client cancel a payment they have already scheduled?",
        a: "No. Once a client schedules a payment for a project, the funds are secured and the payment is locked in. Scheduled payments cannot be cancelled by the client."
      }
    ]
  }
];

export default function Support() {
  const { profile } = useAuth();
  const [searchTerm, setSearchTerm] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  // Filter logic
  const filteredData = FAQ_DATA.map(category => {
    const filteredQuestions = category.questions.filter(
      q => 
        q.q.toLowerCase().includes(searchTerm.toLowerCase()) || 
        q.a.toLowerCase().includes(searchTerm.toLowerCase())
    );
    return { ...category, questions: filteredQuestions };
  }).filter(category => category.questions.length > 0);

  const toggleQuestion = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-card p-6 md:p-8 rounded-2xl border border-border shadow-sm">
        <div className="flex items-start gap-4">
          <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
            <LifeBuoy className="h-6 w-6" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-foreground">Support & FAQ</h2>
            <p className="text-muted-foreground mt-1 font-medium">Find answers to common questions and learn how to navigate the platform.</p>
          </div>
        </div>
      </div>

      {/* Search Bar */}
      <div className="relative">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
        <Input 
          type="text" 
          placeholder="Search for an answer..." 
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full h-14 pl-12 pr-4 rounded-2xl bg-card border border-border text-base focus:ring-2 focus:ring-primary/20 shadow-sm transition-all"
        />
      </div>

      {/* FAQ Accordion */}
      <div className="space-y-6">
        {filteredData.length === 0 ? (
          <Card className="px-6 py-16 text-center border border-border bg-card rounded-2xl shadow-sm flex flex-col items-center">
            <div className="h-16 w-16 rounded-full bg-muted flex items-center justify-center mb-4">
              <Search className="h-8 w-8 text-muted-foreground/50" />
            </div>
            <h4 className="text-lg font-bold text-foreground mb-1">No results found</h4>
            <p className="text-muted-foreground text-sm font-medium">
              We couldn't find any answers matching "{searchTerm}". Try a different keyword.
            </p>
          </Card>
        ) : (
          filteredData.map((category, catIdx) => (
            <div key={catIdx} className="space-y-4">
              <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider flex items-center gap-2 pl-2 pt-4">
                <category.icon className="h-4 w-4" />
                {category.category}
              </h3>
              <div className="space-y-3">
                {category.questions.map((faq, qIdx) => {
                  const id = `${catIdx}-${qIdx}`;
                  const isExpanded = expandedId === id;
                  
                  return (
                    <Card 
                      key={qIdx} 
                      className={cn(
                        "overflow-hidden border transition-all duration-200 shadow-sm",
                        isExpanded ? "border-primary/40 bg-primary/5" : "border-border bg-card hover:border-primary/20 hover:shadow-md"
                      )}
                    >
                      <button
                        onClick={() => toggleQuestion(id)}
                        className="w-full px-6 py-4 flex items-center justify-between text-left focus:outline-none"
                      >
                        <span className={cn(
                          "font-bold pr-4 transition-colors text-sm md:text-base",
                          isExpanded ? "text-primary" : "text-foreground"
                        )}>
                          {faq.q}
                        </span>
                        <div className={cn(
                          "h-8 w-8 rounded-full flex items-center justify-center shrink-0 transition-transform duration-200",
                          isExpanded ? "bg-primary text-primary-foreground rotate-180" : "bg-muted text-muted-foreground"
                        )}>
                          <ChevronDown className="h-4 w-4" />
                        </div>
                      </button>
                      <div 
                        className={cn(
                          "px-6 overflow-hidden transition-all duration-300 ease-in-out text-sm md:text-base",
                          isExpanded ? "max-h-96 pb-5 opacity-100" : "max-h-0 py-0 opacity-0"
                        )}
                      >
                        <p className="text-muted-foreground leading-relaxed border-t border-border/50 pt-4 mt-1">
                          {faq.a}
                        </p>
                      </div>
                    </Card>
                  );
                })}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Contact Support Footer */}
      <Card className="p-8 border border-border bg-gradient-to-br from-card to-muted/30 rounded-2xl shadow-sm mt-8 flex flex-col sm:flex-row items-center justify-between gap-6">
        <div>
          <h3 className="text-xl font-bold text-foreground mb-2">Still need help?</h3>
          <p className="text-muted-foreground text-sm font-medium">Our support team is available to assist you with any platform issues.</p>
        </div>
        <Button className="h-11 px-6 rounded-xl bg-foreground text-background hover:bg-foreground/90 font-bold shadow-md w-full sm:w-auto gap-2">
          <Mail className="h-4 w-4" />
          Contact Support
        </Button>
      </Card>
    </div>
  );
}